apiVersion: apps/v1
kind: Deployment
metadata:
  name: cover-letter-generator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cover-letter-generator
  template:
    metadata:
      labels:
        app: cover-letter-generator
    spec:
      containers:
        - name: cover-letter-generator
          image: cover-letter-generator-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cover-letter-generator-config
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: api-key
            - name: COVER_LETTERS_DIR
              value: "/app/cover_letters"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: cover-letters
              mountPath: /app/cover_letters
      volumes:
        - name: cover-letters
          configMap:
            name: cover-letters-config
